//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKUE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user182_dbEntities : DbContext
    {
        public user182_dbEntities()
            : base("name=user182_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<K_Kvartiry> K_Kvartiry { get; set; }
        public virtual DbSet<K_Pokazaniya> K_Pokazaniya { get; set; }
        public virtual DbSet<K_Polzovateli> K_Polzovateli { get; set; }
        public virtual DbSet<K_Prozhivayushchiye> K_Prozhivayushchiye { get; set; }
        public virtual DbSet<K_Roli> K_Roli { get; set; }
        public virtual DbSet<K_Schetchiki> K_Schetchiki { get; set; }
        public virtual DbSet<K_Tarify> K_Tarify { get; set; }
    }
}
