//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKUE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_Kvartiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public K_Kvartiry()
        {
            this.K_Prozhivayushchiye = new HashSet<K_Prozhivayushchiye>();
            this.K_Schetchiki = new HashSet<K_Schetchiki>();
        }
    
        public int kvartira_id { get; set; }
        public string adres { get; set; }
        public int nomer_kvartiry { get; set; }
        public Nullable<decimal> ploshchad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<K_Prozhivayushchiye> K_Prozhivayushchiye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<K_Schetchiki> K_Schetchiki { get; set; }
    }
}
