//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKUE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_Polzovateli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public K_Polzovateli()
        {
            this.K_Prozhivayushchiye = new HashSet<K_Prozhivayushchiye>();
        }
    
        public int polzovatel_id { get; set; }
        public string login { get; set; }
        public string parol { get; set; }
        public string fio { get; set; }
        public int id_rol { get; set; }
    
        public virtual K_Roli K_Roli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<K_Prozhivayushchiye> K_Prozhivayushchiye { get; set; }
    }
}
