//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKUE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_Pokazaniya
    {
        public int pokazaniye_id { get; set; }
        public System.DateTime data_snyatiya { get; set; }
        public int znacheniye { get; set; }
        public int id_schetchika { get; set; }
    
        public virtual K_Schetchiki K_Schetchiki { get; set; }
    }
}
