//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKUE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_Prozhivayushchiye
    {
        public int prozhivayushchiy_id { get; set; }
        public int id_polzovatelya { get; set; }
        public int id_kvartiry { get; set; }
    
        public virtual K_Kvartiry K_Kvartiry { get; set; }
        public virtual K_Polzovateli K_Polzovateli { get; set; }
    }
}
