//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKUE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_Schetchiki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public K_Schetchiki()
        {
            this.K_Pokazaniya = new HashSet<K_Pokazaniya>();
        }
    
        public int schetchik_id { get; set; }
        public string seriyniy_nomer { get; set; }
        public Nullable<System.DateTime> data_ustanovki { get; set; }
        public int id_kvartiry { get; set; }
        public int id_tipa_resursa { get; set; }
    
        public virtual K_Kvartiry K_Kvartiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<K_Pokazaniya> K_Pokazaniya { get; set; }
    }
}
