//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASKUE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class K_Tarify
    {
        public int tarif_id { get; set; }
        public decimal stoimost_za_edinitsu { get; set; }
        public System.DateTime data_nachala_deystviya { get; set; }
        public Nullable<System.DateTime> data_okonchaniya_deystviya { get; set; }
        public int id_tipa_resursa { get; set; }
    }
}
